version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "UTC"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 15
    target-branch: "main"
    ignore:
      # requires JVM 17
      - dependency-name: "org.junit.jupiter:junit-jupiter"
        versions: "[6.0.1,)"
      # requires JVM 17
      - dependency-name: "com.diffplug.spotless:spotless-maven-plugin"
        versions: "[3.0.0,)"
      # pin 4.1.x for compatibility with Neo4j Kafka Connector v5
      - dependency-name: "io.netty:netty-bom"
        versions: "[4.2.15.Final,)"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "UTC"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 15
    target-branch: "6.0"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    groups:
      dev-deps:
        dependency-type: "development"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    groups:
      dev-deps:
        dependency-type: "development"
    target-branch: "6.0"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    target-branch: "main"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    target-branch: "6.0"
