version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "UTC"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 15
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "UTC"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 15
    target-branch: "6.0"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Etc/GMT"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    target-branch: "main"
    commit-message:
      prefix: "build(repo)"
      prefix-development: "build(repo)"
      include: "scope"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Etc/GMT"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 10
    target-branch: "6.0"
    commit-message:
      prefix: "build(repo)"
      prefix-development: "build(repo)"
      include: "scope"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    target-branch: "main"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    target-branch: "6.0"
