= Neo4j Connector for Kafka
:docs: https://neo4j.com/docs/kafka/quickstart-connect/

The project provides Neo4j sink and source connector implementations for Kafka Connect platform.

== Documentation & Articles

Read more at https://neo4j.com/docs/kafka/

== Feedback & Suggestions

Please raise https://github.com/neo4j/neo4j-kafka-connector/issues[issues on GitHub], we also love contributions, so don't be shy to send a Pull Request.

== Development & Contributions

=== Build locally

First, build and install the `build-resources` module.
----
mvn clean install -f build-resources/pom.xml
----

Then, you can build and package the project using;
----
mvn clean package
----

You'll find the connector archive at `kafka-connect-neo4j/target/components/packages/neo4j-kafka-connect-neo4j-{version}.zip`.

=== Docs

The documentation source for this version lives at https://github.com/neo4j/docs-kafka-connector[this repository].
Please raise any documentation updates by creating a PR against it.

==== License

Neo4j Streams is licensed under the terms of the Apache License, version 2.0.  See `LICENSE` for more details. 
