package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("github-commit-status-token", "%github-token%")
        }
        update {
            password("github-commit-status-token", "credentialsJSON:aff97f80-6681-4b35-b1d8-a51be283851e")
        }
        expect {
            password("github-pull-request-token", "%github-token%")
        }
        update {
            password("github-pull-request-token", "credentialsJSON:aff97f80-6681-4b35-b1d8-a51be283851e")
        }
    }
}
